"""Training, checkpointing, and inference for ATCG-FM models."""

from atcg.runtime.batching import (
    CausalBatch,
    StatefulCausalBatch,
    collate_examples,
    collate_horizons,
)
from atcg.runtime.checkpoint import (
    LoadedCheckpoint,
    load_checkpoint,
    load_model_checkpoint,
    save_checkpoint,
)
from atcg.runtime.comparison import (
    ComparisonCandidate,
    ComparisonInvariants,
    ComparisonPlan,
    SubstitutionUnit,
)
from atcg.runtime.inference import (
    GenerationResult,
    IndependentSequenceOutput,
    SequenceScore,
    StatefulInferencePolicy,
    forward_independent_sequences,
    generate,
    score_sequence,
)
from atcg.runtime.ordered_comparison import (
    CudaUtilizationSampler,
    MicrobatchMeasurement,
    OffsetValidationMetrics,
    OrderedComparisonConfig,
    OrderedComparisonTrainer,
    OrderedStepMetrics,
    OrderedValidationMetrics,
    ProfileMeasurement,
    RepeatContextMetrics,
    benchmark_ordered_candidate,
    ordered_dataset_fingerprint,
    restore_ordered_trainer,
    select_largest_fitting_profile,
    train_ordered_epoch,
    validate_ordered_model,
    validate_repeat_contexts,
)
from atcg.runtime.stateful import StatefulTrainer, StreamStateStore, fit_stateful
from atcg.runtime.training import (
    StepMetrics,
    Trainer,
    TrainingConfig,
    TrainingRun,
    fit,
)
from atcg.runtime.training_state import TrainingState
from atcg.runtime.validation import CausalValidationMetrics, validate_causal_language_model

__all__ = [
    "CausalBatch",
    "CausalValidationMetrics",
    "ComparisonCandidate",
    "ComparisonInvariants",
    "ComparisonPlan",
    "CudaUtilizationSampler",
    "GenerationResult",
    "IndependentSequenceOutput",
    "LoadedCheckpoint",
    "MicrobatchMeasurement",
    "OffsetValidationMetrics",
    "OrderedComparisonConfig",
    "OrderedComparisonTrainer",
    "OrderedStepMetrics",
    "OrderedValidationMetrics",
    "ProfileMeasurement",
    "RepeatContextMetrics",
    "SequenceScore",
    "StatefulCausalBatch",
    "StatefulInferencePolicy",
    "StatefulTrainer",
    "StepMetrics",
    "StreamStateStore",
    "SubstitutionUnit",
    "Trainer",
    "TrainingConfig",
    "TrainingRun",
    "TrainingState",
    "benchmark_ordered_candidate",
    "collate_examples",
    "collate_horizons",
    "fit",
    "fit_stateful",
    "forward_independent_sequences",
    "generate",
    "load_checkpoint",
    "load_model_checkpoint",
    "ordered_dataset_fingerprint",
    "restore_ordered_trainer",
    "save_checkpoint",
    "score_sequence",
    "select_largest_fitting_profile",
    "train_ordered_epoch",
    "validate_causal_language_model",
    "validate_ordered_model",
    "validate_repeat_contexts",
]
